In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array, type(my_list), type(my_array)

(array([1, 2, 3, 4, 5]), list, numpy.ndarray)

In [3]:
my_array.dtype

dtype('int64')

In [4]:
my_array.shape

(5,)

In [5]:
import numpy as np

zeros_array = np.zeros((2, 3))    # 2x3 array of zeros
ones_array = np.ones((3, 3))      # 3x3 array of ones
full_array = np.full((2, 2), 7)    # 2x2 array filled with 7
range_array = np.arange(0, 10, 2)  # array with values from 0 to 8 with a step of 2
linspace_array = np.linspace(0, 1, 5)  # array with 5 evenly spaced values between 0 and 1

print("Array of zeros:\n", zeros_array)
print("Array of ones:\n", ones_array)
print("Array of sevens:\n", full_array)
print("Array of range:\n", range_array)
print("Array of linspace:\n", linspace_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of sevens:
 [[7 7]
 [7 7]]
Array of range:
 [0 2 4 6 8]
Array of linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [6]:
ones_array *0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
import numpy as np

# 1-D array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:\n", arr)
print("Shape of array: ", arr.shape, "\n")

# Operations along the axis
print("Sum: ", np.sum(arr, axis=0))
print("Min: ", np.min(arr, axis=0))
print("Max: ", np.max(arr, axis=0))
print("Mean: ", np.mean(arr, axis=0))

Original array:
 [1 2 3 4 5]
Shape of array:  (5,) 

Sum:  15
Min:  1
Max:  5
Mean:  3.0


In [12]:
arr.sum(), arr.max(), arr.min(), arr.mean(), arr.std()

(15, 5, 1, 3.0, 1.4142135623730951)

In [13]:
# 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)
print("Shape of array: ", arr.shape, "\n")

# Operations along axis 0
print("Sum along axis 0:\n", np.sum(arr, axis=0))
print("Min along axis 0:\n", np.min(arr, axis=0))
print("Max along axis 0:\n", np.max(arr, axis=0))
print("Mean along axis 0:\n", np.mean(arr, axis=0))

# Operations along axis 1
print("Sum along axis 1:\n", np.sum(arr, axis=1))
print("Min along axis 1:\n", np.min(arr, axis=1))
print("Max along axis 1:\n", np.max(arr, axis=1))
print("Mean along axis 1:\n", np.mean(arr, axis=1))

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of array:  (3, 3) 

Sum along axis 0:
 [12 15 18]
Min along axis 0:
 [1 2 3]
Max along axis 0:
 [7 8 9]
Mean along axis 0:
 [4. 5. 6.]
Sum along axis 1:
 [ 6 15 24]
Min along axis 1:
 [1 4 7]
Max along axis 1:
 [3 6 9]
Mean along axis 1:
 [2. 5. 8.]


In [14]:
# 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original array:\n", arr)
print("Shape of array: ", arr.shape, "\n")

# Operations along axis 0
print("Sum along axis 0:\n", np.sum(arr, axis=0))
print("Min along axis 0:\n", np.min(arr, axis=0))
print("Max along axis 0:\n", np.max(arr, axis=0))
print("Mean along axis 0:\n", np.mean(arr, axis=0))

# Operations along axis 1
print("Sum along axis 1:\n", np.sum(arr, axis=1))
print("Min along axis 1:\n", np.min(arr, axis=1))
print("Max along axis 1:\n", np.max(arr, axis=1))
print("Mean along axis 1:\n", np.mean(arr, axis=1))

# Operations along axis 2
print("Sum along axis 2:\n", np.sum(arr, axis=2))
print("Min along axis 2:\n", np.min(arr, axis=2))
print("Max along axis 2:\n", np.max(arr, axis=2))
print("Mean along axis 2:\n", np.mean(arr, axis=2))

Original array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of array:  (2, 2, 3) 

Sum along axis 0:
 [[ 8 10 12]
 [14 16 18]]
Min along axis 0:
 [[1 2 3]
 [4 5 6]]
Max along axis 0:
 [[ 7  8  9]
 [10 11 12]]
Mean along axis 0:
 [[4. 5. 6.]
 [7. 8. 9.]]
Sum along axis 1:
 [[ 5  7  9]
 [17 19 21]]
Min along axis 1:
 [[1 2 3]
 [7 8 9]]
Max along axis 1:
 [[ 4  5  6]
 [10 11 12]]
Mean along axis 1:
 [[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]]
Sum along axis 2:
 [[ 6 15]
 [24 33]]
Min along axis 2:
 [[ 1  4]
 [ 7 10]]
Max along axis 2:
 [[ 3  6]
 [ 9 12]]
Mean along axis 2:
 [[ 2.  5.]
 [ 8. 11.]]


In [15]:
my_array

array([1, 2, 3, 4, 5])

In [17]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:

# Create a mask
mask = arr > 5
print("Mask:", mask)

Mask: [False False False False False False  True  True  True  True  True]


In [20]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [22]:
arr[mask] = 10

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5, 10, 10, 10, 10, 10])

In [27]:
arr= np.array([0,1,2,3,4,5,10,12,8,9,10])

np.where(arr>5)

(array([ 6,  7,  8,  9, 10]),)